version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t lambda_berlin .
      - docker tag lambda_berlin:latest 915485756489.dkr.ecr.us-east-1.amazonaws.com/lambda_berlin:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 915485756489.dkr.ecr.us-east-1.amazonaws.com/lambda_berlin:latest
